[package]
name = "rusty"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.7.0"
clap = { version = "4.1.11", features = ["derive"] }
ureq = "2.7.1"
sha256 = "1.1.4"
